---
title: "Lab 02 - Merge conflicts and collaboration on github"
output: 
  tufte::tufte_html:
    tufte_variant: "envisioned"
    highlight: pygments
    css: ../lab.css
link-citations: yes
---

```{r include = FALSE}
knitr::opts_chunk$set(eval = FALSE)
```


# Learning goals

-   Collaborating on GitHub and resolving merge conflicts

**Before Lab**: Read about merge conflicts below. The merge conflict exercise we'll start with during the lab will assume that you have this background information.

## Merges and merge conflicts

We're going to do all our labs in teams, so we're going to make things a little more interesting and let all of you make changes and push those changes to your team repository.
Sometimes things will go swimmingly, and sometimes you'll run into merge conflicts.
So our first task today is to walk you through a merge conflict!

-   Pushing to a repo replaces the code on GitHub with the code you have on your computer.
-   If a collaborator has made a change to your repo on GitHub that you haven't incorporated into your local work, GitHub will stop you from pushing to the repo because this could overwrite your collaborator's work!
-   So you need to explicitly "merge" your collaborator's work with the project state on your computer before you can push.
-   If your and your collaborator's changes are in different files or in different parts of the same file, git merges the work for you automatically when you \*pull\*.
-   If you both changed the same part of a file, git will produce a \*\*merge conflict\*\* because it doesn't know how which change you want to keep and which change you want to overwrite.

Git will put conflict markers in your code that look like:
<pre>
<<<<<<< HEAD 

<span style = "color:orange">See also: [dplyr documentation](https://dplyr.tidyverse.org/)</span>

======= 

<span style = "color:blue">See also [ggplot2 documentation](https://ggplot2.tidyverse.org/)</span>

>>>>>>> some1alpha2numeric3string4
</pre>

The `===`s separate <span style = "color:orange">*your* changes (top)</span> from <span style = "color:blue">*their* changes (bottom).</span>

Note that on top you see the word `HEAD`, which indicates that these are your changes.
```{marginfigure}
Memonic: It's YOUR HEAD, and they both have four letters.
```

And at the bottom you see `some1alpha2numeric3string4` (well, it probably looks more like `28e7b2ceb39972085a0860892062810fb812a08f`).

This is the **hash** (a unique identifier) of the commit your collaborator made with the conflicting change.

Your job is to *reconcile* the changes: edit the file so that it incorporates the best of both versions and delete the `<<<`, `===`, and `>>>` lines.
Then you can stage and commit the result.

# Merge conflict activity

## Setup

-   Clone the repo and open the .Rmd file.
-   Assign the numbers 1, 2, 3, 4, and 5 to each of the team members. If your team has fewer than 5 people, some people will need to have multiple numbers. If your team has more than 5 people, some people will need to share some numbers.

## Let's cause a merge conflict!

Our goal is to see two different types of merges: first we'll see a type of merge that git can't figure out on its own how to do on its own (a **merge conflict**) and requires human intervention, then another type of merge where git can figure out how to merge without human intervention.

Doing this will require some tight choreography, so pay attention!

Take turns in completing the exercise, only one member at a time.
**Others should just watch, not doing anything on their own projects (this includes not even pulling changes!)** until they are instructed to.
I recommend putting your hands in your pockets or sitting on them when it's not your turn!

**Before starting**: everyone should have the repo cloned and know which role number they are.

**Role 1:**

-   Change the team name to your actual team name.
-   Knit, commit, push.

🛑 Make sure the previous role has finished before moving on to the next step.

**Role 2:**

-   Change the team name to some other word.
-   Knit, commit, push. You should get an error.
-   Pull. Take a look at the document with the merge conflict.
-   Clear the merge conflict by editing the document to choose the correct/preferred change.
-   Knit.
-   **Click the Stage checkbox** for all files in your Git tab. Make sure they all have check marks, not a blue filled-in square.
-   Commit and push.

🛑 Make sure the previous role has finished before moving on to the next step.

**Role 3:**

-   Change the a label of the first code chunk
-   Knit, commit, push. You should get an error.
-   Pull. No merge conflicts should occur, but you should see a message about merging.
-   Now push.

🛑 Make sure the previous role has finished before moving on to the next step.

**Role 4 (pick anyone except the Role 3 participant)**

-   Change the label of the first code chunk to something other than previous role did.
-   Knit, commit, push. You should get an error.
-   Pull. Take a look at the document with the merge conflict. Clear the merge conflict by choosing the correct/preferred change. Commit, and push.

🛑 Make sure the previous role has finished before moving on to the next step.

**Role 5:**

-   Change the R code inside the first code chunk
-   Knit, commit, push. You should get an error.
-   Pull. No merge conflicts should occur, but you should see a message about merging.
-   Now push.

🛑 Make sure the previous role has finished before moving on to the next step.

**Everyone:** Pull, and observe the changes in your document.  

Discuss the following questions in your group: 

1.  does anyone need to push anything at this point for the exercise to be completed as far as your instructors or TAs are concerned?
2.  Does anyone need to pull anything at this point for their local version of the repository to be complete?  If so, go ahead and do this.

## Tips for collaborating via GitHub

-   Always pull first before you start working.
-   Resolve a merge conflict (commit and push) *before* continuing your work. Never do new work while resolving a merge conflict.
-   Knit, commit, and push often to minimize merge conflicts and/or to make merge conflicts easier to resolve.
-   If you find yourself in a situation that is difficult to resolve, ask questions ASAP. Don't let it linger and get bigger.

## Rubric (15 points possible)

4 points if questions 1 and 2 have answers added as text.
5 points for >= five commits with informative messages made to the repo.
6 points for commits being from alternating team members following the directions above to create and resolve merge conflicts.
